object Versions {

    const val androidMaterialVersion = "1.3.0"
    const val appCompatVersion = "1.2.0"
    const val cardViewVersion = "1.0.0"
    const val coilVersion = "1.2.0"
    const val constraintLayoutVersion = "1.3.2"
    const val coroutinesVersion = "1.4.2"
    const val coreKtxVersion = "1.3.2"
    const val daggerHiltVersion = "2.33-beta"
    const val espressoVersion = "3.3.0"
    const val fragmentKtxVersion = "1.3.2"
    const val glideVersion = "4.12.0"
    const val gradleVersion = "4.1.3"
    const val junitExtensionsVersion = "1.1.2"
    const val junitVersion = "4.13.2"
    const val kotlinVersion = "1.4.31"
    const val ktlintVersion = "0.41.0"
    const val liveDataKtxVersion = "2.3.1"
    const val moshiVersion = "1.12.0"
    const val navigationVersion = "2.3.5"
    const val okhttp3Version = "5.0.0-alpha.2"
    const val retrofit2MoshiConvertorVersion = "2.4.0"
    const val retrofit2Version = "2.9.0"
    const val swipeRefreshLayoutVersion = "1.1.0"
    const val viewModelKtxVersion = "2.3.1"
}
